function org_Y_Game(){var db='',ab=' top: -1000px;',Ab='" for "gwt:onLoadErrorFn"',yb='" for "gwt:onPropertyErrorFn"',jb='");',Bb='#',Nb='&',tc='.cache.js',Db='/',Jb='//',cc='1AD8878D091DD8C32056E90CB4EE5B75',dc='1E9C64FA214B3DF0F79A6CD720D342B1',ec='5D405667635AAA8E358F81C9884BBC62',gc='78E103EB0C5979EEF84AF0BC8EF0B29C',hc='7E959EB5D3FC8D07039F1D29DD617399',ic='9066D8689E02ED0BF18D7260B3FD2903',jc='9870B62A46DAB03DC80434A159C37724',sc=':',sb='::',Fc=':moduleBase',cb='<!doctype html>',eb='<html><head><\/head><body><\/body><\/html>',vb='=',Cb='?',kc='A0DD7C90D38BF368E2A3DB951C6F878F',lc='A3DB04FF986EE458D89B2D9A54D360A5',mc='B1BEF6FC636633C83902ABD8BD887EC0',nc='BC50AC618BF5D9C6AEF1EEB8F1ECC255',xb='Bad handler "',bb='CSS1Compat',hb='Chrome',oc='D3ABD48D2DB0B8771985F60A4788FDB4',pc='DDA0D1B217A74F3BE9F9EE615635039B',gb='DOMContentLoaded',X='DUMMY',qc='EC36D9B8481AB15475201549A7A15163',rc='F7633E4EA95BF8FC18D5147606F40635',Ec='Ignoring non-whitelisted Dev Mode URL: ',Qb='Unexpected exception in locale detection, using default: ',Pb='_',Dc='__gwtDevModeHook:org.Y_Game',Ob='__gwt_Locale',Ib='base',Gb='baseUrl',S='begin',Y='body',R='bootstrap',Fb='clear.cache.gif',ub='content',fc='default',bc='en',Ac='end',ib='eval("',Cc='file:',Yb='gecko',Zb='gecko1_8',T='gwt.codesvr.org.Y_Game=',U='gwt.codesvr=',zc='gwt/clean/clean.css',zb='gwt:onLoadErrorFn',wb='gwt:onPropertyErrorFn',tb='gwt:property',ob='head',xc='href',Bc='http:',Vb='ie10',Xb='ie8',Wb='ie9',Z='iframe',Eb='img',lb='javascript',$='javascript:""',uc='link',yc='loadExternalRefs',Kb='locale',Mb='locale=',pb='meta',nb='moduleRequested',mb='moduleStartup',Ub='msie',qb='name',V='org.Y_Game',ac='org.Y_Game.devmode.js',Hb='org.Y_Game.nocache.js',rb='org.Y_Game::',_='position:absolute; width:0; height:0; border:none; left: -1000px;',vc='rel',Tb='safari',kb='script',_b='selectingPermutation',W='startup',wc='stylesheet',fb='undefined',$b='unknown',Rb='user.agent',Sb='webkit',Lb='zh';var q=window;var r=document;t(R,S);function s(){var a=q.location.search;return a.indexOf(T)!=-1||a.indexOf(U)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:V,sessionId:q.__gwtStatsSessionId,subSystem:W,evtGroup:a,millis:(new Date).getTime(),type:b})}}
org_Y_Game.__sendStats=t;org_Y_Game.__moduleName=V;org_Y_Game.__errFn=null;org_Y_Game.__moduleBase=X;org_Y_Game.__softPermutationId=0;org_Y_Game.__computePropValue=null;org_Y_Game.__getPropMap=null;org_Y_Game.__gwtInstallCode=function(){};org_Y_Game.__gwtStartLoadingFragment=function(){return null};var u=function(){return false};var v=function(){return null};__propertyErrorFunction=null;var w=q.__gwt_activeModules=q.__gwt_activeModules||{};w[V]={moduleName:V};var A;function B(){D();return A}
function C(){D();return A.getElementsByTagName(Y)[0]}
function D(){if(A){return}var a=r.createElement(Z);a.src=$;a.id=V;a.style.cssText=_+ab;a.tabIndex=-1;r.body.appendChild(a);A=a.contentDocument;if(!A){A=a.contentWindow.document}A.open();var b=document.compatMode==bb?cb:db;A.write(b+eb);A.close()}
function F(k){function l(a){function b(){if(typeof r.readyState==fb){return typeof r.body!=fb&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(r.removeEventListener){r.removeEventListener(gb,d,false)}if(e){clearInterval(e)}}}
if(r.addEventListener){r.addEventListener(gb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=C();var f=B();var g;if(navigator.userAgent.indexOf(hb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(ib));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(jb));g=f.createElement(kb);g.language=lb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(kb);g.language=lb;g.text=c[i];e.appendChild(g);d(e,g)}}}
org_Y_Game.onScriptDownloaded=function(a){l(function(){m(a)})};t(mb,nb);var n=r.createElement(kb);n.src=k;r.getElementsByTagName(ob)[0].appendChild(n)}
org_Y_Game.__startLoadingFragment=function(a){return I(a)};org_Y_Game.__installRunAsyncCode=function(a){var b=C();var c=B().createElement(kb);c.language=lb;c.text=a;b.appendChild(c);b.removeChild(c)};function G(){var c={};var d;var e;var f=r.getElementsByTagName(pb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,db);if(j.indexOf(sb)>=0){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=db}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}v=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;org_Y_Game.__errFn=e}
function H(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=0?a.substring(0,d+1):db}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(Eb);b.src=a+Fb;a=e(b.src)}return a}
function g(){var a=v(Gb);if(a!=null){return a}return db}
function h(){var a=r.getElementsByTagName(kb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Hb)!=-1){return e(a[b].src)}}return db}
function i(){var a=r.getElementsByTagName(Ib);if(a.length>0){return a[a.length-1].href}return db}
function j(){var a=r.location;return a.href==a.protocol+Jb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==db){k=h()}if(k==db){k=i()}if(k==db&&j()){k=e(r.location.href)}k=f(k);return k}
function I(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return org_Y_Game.__moduleBase+a}
function J(){var i=[];var j;function k(a,b){var c=i;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
m[Kb]=function(){var b=null;var c=Lb;try{if(!b){var d=location.search;var e=d.indexOf(Mb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Nb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=v(Kb)}if(!b){b=q[Ob]}if(b){c=b}while(b&&!u(Kb,b)){var h=b.lastIndexOf(Pb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Qb+a)}q[Ob]=c;return b||Lb};l[Kb]={'default':0,en:1,zh:2};m[Rb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Sb)!=-1}())return Tb;if(function(){return b.indexOf(Ub)!=-1&&r.documentMode>=10}())return Vb;if(function(){return b.indexOf(Ub)!=-1&&r.documentMode>=9}())return Wb;if(function(){return b.indexOf(Ub)!=-1&&r.documentMode>=8}())return Xb;if(function(){return b.indexOf(Yb)!=-1}())return Zb;return $b};l[Rb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};u=function(a,b){return b in l[a]};org_Y_Game.__getPropMap=function(){var a={};for(var b in l){if(l.hasOwnProperty(b)){a[b]=n(b)}}return a};org_Y_Game.__computePropValue=n;q.__gwt_activeModules[V].bindings=org_Y_Game.__getPropMap;t(R,_b);if(s()){return I(ac)}var o;try{k([bc,Tb],cc);k([Lb,Vb],dc);k([Lb,Zb],ec);k([fc,Zb],gc);k([bc,Vb],hc);k([bc,Zb],ic);k([Lb,Wb],jc);k([fc,Wb],kc);k([bc,Xb],lc);k([bc,Wb],mc);k([fc,Tb],nc);k([Lb,Xb],oc);k([fc,Vb],pc);k([fc,Xb],qc);k([Lb,Tb],rc);o=i[n(Kb)][n(Rb)];var p=o.indexOf(sc);if(p!=-1){j=parseInt(o.substring(p+1),10);o=o.substring(0,p)}}catch(a){}org_Y_Game.__softPermutationId=j;return I(o+tc)}
function K(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=r.createElement(uc);b.setAttribute(vc,wc);b.setAttribute(xc,I(a));r.getElementsByTagName(ob)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
t(yc,S);c(zc);t(yc,Ac)}
G();org_Y_Game.__moduleBase=H();w[V].moduleBase=org_Y_Game.__moduleBase;var L=J();if(q){var M=!!(q.location.protocol==Bc||q.location.protocol==Cc);q.__gwt_activeModules[V].canRedirect=M;if(M){var N=Dc;var O=q.sessionStorage[N];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(O)){if(O&&(window.console&&console.log)){console.log(Ec+O)}O=db}if(O&&!q[N]){q[N]=true;q[N+Fc]=H();var P=r.createElement(kb);P.src=O;var Q=r.getElementsByTagName(ob)[0];Q.insertBefore(P,Q.firstElementChild||Q.children[0]);return false}}}K();t(R,Ac);F(L);return true}
org_Y_Game.succeeded=org_Y_Game();